name: Auto Release

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Get commit count
      id: vars
      shell: bash
      run: |
        echo "BUILD_NUMBER=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
        
    - name: Build
      run: |
        go mod tidy
        go build -v -o dist/server-tools.exe ./exe/main.go
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: build-${{ steps.vars.outputs.BUILD_NUMBER }}
        name: 自动发布 #${{ steps.vars.outputs.BUILD_NUMBER }}
        files: |
          dist/server-tools.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}