name: Manual Build - Server Tools

on:
  workflow_dispatch: # 仅支持手动触发

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Get date for version
        id: version
        shell: bash
        run: |
          VERSION="server-tools-$(date +'%Y%m%d')"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          mkdir -p dist
          go mod tidy
          go build -v -o dist/server-tools.exe ./exe/main.go

      - name: Install GitHub CLI
        run: choco install gh -y
        shell: powershell

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.version.outputs.VERSION }}" dist/server-tools.exe `
            --title "${{ steps.version.outputs.VERSION }}" `
            --notes "Manual build of server-tools on $(date +'%Y-%m-%d')"
